name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: lukka/get-cmake@latest
      - name: Download and install Boost
        uses: MarkusJx/install-boost@v2.5.1
        with:
          boost_version: 1.89.0
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: lukka/get-cmake@latest
      - name: Download and install Boost
        uses: MarkusJx/install-boost@v2.5.1
        with:
          boost_version: 1.89.0
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run benchmarks
        run: build/WebServer
